spring:
  application:
    name: code-reviewer
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    open-in-view: false

app:
  github:
    webhook-secret: ${GITHUB_WEBHOOK_SECRET}
    token: ${GITHUB_TOKEN}

logging:
  level:
    com.personalProject.code_reviewer: DEBUG